version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template \
          --template-body file://template.yml

      - echo "Deploying Lambda unload job stack..."
      - aws cloudformation deploy \
          --template-file template.yml \
          --stack-name lambda-unload-job-stack \
          --region us-east-1
