version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
       aws cloudformation deploy \
         --template-body file://template.yml \
         --stack-name lambda-unload-job-stack \
         --region us-east-1
