version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - aws cloudformation deploy --stack-name Lambda-unload-job-stack --template-file template.yml --region us-east-1
artificats:
  files:
    - dummy.txt
      


