version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name Lambda-unload-job-stack \
          --region us-east-1 \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
      - echo " eployment complete. Creating artifact..."
      - echo "Build completed successfully" > build-output.txt

artifacts:
  files:
    - build-output.txt
