version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Listing files in working directory..."
      - ls -la

      - echo "Showing contents of template.yml..."
      - cat template.yml

      - echo "Deploying Lambda unload job stack..."
      - aws cloudformation deploy \
          --stack-name lambda-unload-job-stack \
          --template-file template.yml \
          --region us-east-1
