version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - aws cloudformation deploy --template-file template.yml --stack-name Lambda-unload-job-stack
      - echo "Build completed successfully" > build-output.txt

artifacts:
  files:
    - build-output.txt
